join-message:
  - "&7+ %vault_prefix% &8| &7%player_displayname%"
leave-message:
  - "&7- %vault_prefix% &8| &7%player_displayname%"
token:
  # 1 token for every $1000
  conversion-rate: "1:1000"
  give-command: "give %player_name% amethyst_shard %amount% name:&dToken durability:1 ItemFlags:HIDE_ENCHANTS"