name: @name@
version: @version@
description: A MineHut Core plugin
author: yakovliam
website: https://yakovliam.com
main: com.yakovliam.minehutcore.MineHutCorePlugin
api-version: 1.17
depend:
  - SpaceStatistics
  - ProtocolLib
  - Vault

